name: tests

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go: ["1.21"]
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go @ ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Tests
        run: |
          make test
